version: '2'
services:
  # Auto generates the properties files for all services and the nginx config
  configs:
    image: python:2.7
    entrypoint: /entrypoint.sh
    volumes:
      - .:/code
      - ./docker/entrypoints/configs.sh:/entrypoint.sh
      - configs-vol:/configs
      - $HOME/.aws/:/root/.aws:ro
      - $HOME/.gu/grid/:/root/.gu/grid

  elasticsearch:
    build:
      context: ./docker
      dockerfile: Dockerfile-elastic
    expose:
      - "9200"
      - "9300"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "./docker/configs/elasticsearch:/usr/share/elasticsearch/config"
    restart: unless-stopped

  # Base container for sbt-based services.
  sbt:
    build:
      context: ./docker
      dockerfile: Dockerfile-sbt
    expose:
      - "9000"
    entrypoint: /entrypoint.sh
    volumes:
      - ./:/code
      - ./docker/entrypoints/sbt.sh:/entrypoint.sh
      - configs-vol:/configs
      - ivy-vol:/root/.ivy2
      - sbt-vol:/root/.sbt
    restart: unless-stopped

  media-api:
    environment:
      APP: media-api
    extends:
      service: sbt
    depends_on:
      - configs
      - elasticsearch
  thrall:
    environment:
      APP: thrall
    extends:
      service: sbt
    depends_on:
      - configs
      - elasticsearch
  image-loader:
    environment:
      APP: image-loader
    extends:
      service: sbt
    depends_on:
      - configs
  kahuna:
    environment:
      APP: kahuna
    extends:
      service: sbt
    depends_on:
      - configs
  cropper:
    environment:
      APP: cropper
    extends:
      service: sbt
    depends_on:
      - configs
  metadata-editor:
    environment:
      APP: metadata-editor
    extends:
      service: sbt
    depends_on:
      - configs
  usage:
    environment:
      APP: usage
    extends:
      service: sbt
    depends_on:
      - configs
  collections:
    environment:
      APP: collections
    extends:
      service: sbt
    depends_on:
      - configs

  imgops:
    build:
      context: ./docker
      dockerfile: Dockerfile-imgops
    depends_on:
      - configs
    entrypoint: /entrypoint.sh
    volumes:
      - ./docker/entrypoints/imgops.sh:/entrypoint.sh
      - configs-vol:/configs

  # Proxy server for all services
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - elasticsearch
      - configs
      - media-api
      - thrall
      - image-loader
      - kahuna
      - cropper
      - metadata-editor
      - usage
      - collections
      - imgops
    entrypoint: /entrypoint.sh
    volumes:
      - configs-vol:/configs
      - ./docker/entrypoints/nginx.sh:/entrypoint.sh

volumes:
  configs-vol:
    driver: local
  ivy-vol:
    driver: local
  sbt-vol:
    driver: local
