version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    volumes:
      - "./elasticsearch/dev/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ports:
      - "9200:9200"
  imgops:
    build:
      context: ./imgops/dev
    ports:
      - "9008:80"
    volumes:
      - "./imgops/dev/nginx.conf:/etc/nginx/nginx.conf"
  cerebro:
    image: lmenezes/cerebro
    ports:
      - "9090:9000"
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kinesis,dynamodb
      - DEFAULT_REGION=eu-west-1
      - KINESIS_ERROR_PROBABILITY=0.0
