version: '3'
services:
  elasticsearch:
    image: elasticsearch:1.7.1
    volumes:
      - "./elasticsearch/test/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ports:
      - "9201:9200"
      - "9301:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  elasticsearch6:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    volumes:
     - "./elasticsearch6/test/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ports:  
      - "9206:9200"
      - "9306:9300"
