apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - port: 9011
      name: auth
      nodePort: 32111
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: guardiangrid/auth:sihil_dockerise
          ports:
            - containerPort: 9011
          volumeMounts:
            - name: config-volume
              mountPath: /etc/grid
          resources:
            limits:
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /management/healthcheck
              port: 9011
            initialDelaySeconds: 30
            periodSeconds: 3
      volumes:
        - name: config-volume
          configMap:
            name: auth
