data:
  image: java:openjdk-8-jdk
  volumes:
    - "$HOME/.ivy2:/root/.ivy2"
    - "../:/home/code"
    - "$HOME/.gu:/etc/gu:ro"
elastic:
  build: .
  dockerfile: Dockerfile-elastic
  container_name: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - "../elasticsearch/config:/usr/share/elasticsearch/config"
  restart: unless-stopped
media-api:
  environment:
    APP: media-api
  extends:
    file: grid-core.yml
    service: sbt
  links:
    - elastic
  ports:
    - "9001:9000"
  volumes_from:
    - data
thrall:
  environment:
    APP: thrall
  extends:
    file: grid-core.yml
    service: sbt
  links:
    - elastic
  ports:
    - "9002:9000"
  volumes_from:
    - data
image-loader:
  environment:
    APP: image-loader
  extends:
    file: grid-core.yml
    service: sbt-imaging
  ports:
    - "9003:9000"
  volumes_from:
    - data
kahuna:
  environment:
    APP: kahuna
  extends:
    file: grid-core.yml
    service: sbt
  ports:
    - "9005:9000"
  volumes_from:
    - data
cropper:
  environment:
    APP: cropper
  extends:
    file: grid-core.yml
    service: sbt-imaging
  ports:
    - "9006:9000"
  volumes_from:
    - data
metadata-editor:
  environment:
    APP: metadata-editor
  extends:
    file: grid-core.yml
    service: sbt
  ports:
    - "9007:9000"
  volumes_from:
    - data
usage:
  environment:
    APP: usage
  extends:
    file: grid-core.yml
    service: sbt
  ports:
    - "9009:9000"
  volumes_from:
    - data
collections:
  environment:
    APP: collections
  extends:
    file: grid-core.yml
    service: sbt
  ports:
    - "9010:9000"
  volumes_from:
    - data
