data:
  image: java:openjdk-8-jdk
  volumes:
    - "$HOME/.ivy2:/root/.ivy2"
    - "../:/home/code"
    - "$HOME/.gu:/etc/gu:ro"
nginx:
  image: nginx:latest
  links:
    - elasticsearch
    - media-api
    - thrall
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    - "./nginx/sites-enabled:/etc/nginx/sites-enabled:ro"
elasticsearch:
  build: .
  dockerfile: Dockerfile-elastic
  container_name: elasticsearch
  expose:
    - "9200"
    - "9300"
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - "../elasticsearch/config:/usr/share/elasticsearch/config"
  restart: unless-stopped
media-api:
  environment:
    APP: media-api
  extends:
    file: grid-core.yml
    service: sbt
  links:
    - elasticsearch
  volumes_from:
    - data
thrall:
  environment:
    APP: thrall
  extends:
    file: grid-core.yml
    service: sbt
  links:
    - elasticsearch
  volumes_from:
    - data
image-loader:
  environment:
    APP: image-loader
  extends:
    file: grid-core.yml
    service: sbt-imaging
  volumes_from:
    - data
kahuna:
  environment:
    APP: kahuna
  extends:
    file: grid-core.yml
    service: sbt
  volumes_from:
    - data
cropper:
  environment:
    APP: cropper
  extends:
    file: grid-core.yml
    service: sbt-imaging
  volumes_from:
    - data
metadata-editor:
  environment:
    APP: metadata-editor
  extends:
    file: grid-core.yml
    service: sbt
  volumes_from:
    - data
usage:
  environment:
    APP: usage
  extends:
    file: grid-core.yml
    service: sbt
  volumes_from:
    - data
collections:
  environment:
    APP: collections
  extends:
    file: grid-core.yml
    service: sbt
  volumes_from:
    - data
