configs:
  build: .
  dockerfile: Dockerfile-configs
  volumes:
    - "./entrypoints:/entrypoints"
    - "./configs/generators:/configs/generators"
    - "$HOME/.aws/:/home/grid/.aws:ro"
    - "$HOME/.gu/grid/:/home/grid/.gu/grid"
    - "/configs"
  entrypoint: /entrypoints/configs.sh
  user: grid
nginx:
  image: nginx:latest
  links:
    - elasticsearch
    - media-api
    - thrall
    - image-loader
    - kahuna
    - cropper
    - metadata-editor
    - usage
    - collections
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "./entrypoints:/entrypoints"
    - "./configs/nginx.conf:/etc/nginx/nginx.conf"
  volumes_from:
    - configs
  entrypoint: /entrypoints/nginx.sh
data:
  image: python:2.7
  volumes:
    - "../:/code"
elasticsearch:
  build: .
  dockerfile: Dockerfile-elastic
  container_name: elasticsearch
  expose:
    - "9200"
    - "9300"
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - "./configs/elasticsearch:/usr/share/elasticsearch/config"
  restart: unless-stopped
media-api:
  environment:
    APP: media-api
  extends:
    file: docker-compose-sbt.yml
    service: sbt
  links:
    - elasticsearch
  volumes_from:
    - configs
    - data
thrall:
  environment:
    APP: thrall
  extends:
    file: docker-compose-sbt.yml
    service: sbt
  links:
    - elasticsearch
  volumes_from:
    - configs
    - data
image-loader:
  environment:
    APP: image-loader
  extends:
    file: docker-compose-sbt.yml
    service: sbt
  volumes_from:
    - configs
    - data
kahuna:
  environment:
    APP: kahuna
  extends:
    file: docker-compose-sbt.yml
    service: sbt
  volumes_from:
    - configs
    - data
cropper:
  environment:
    APP: cropper
  extends:
    file: docker-compose-sbt.yml
    service: sbt
  volumes_from:
    - configs
    - data
metadata-editor:
  environment:
    APP: metadata-editor
  extends:
    file: docker-compose-sbt.yml
    service: sbt
  volumes_from:
    - configs
    - data
usage:
  environment:
    APP: usage
  extends:
    file: docker-compose-sbt.yml
    service: sbt
  volumes_from:
    - configs
    - data
collections:
  environment:
    APP: collections
  extends:
    file: docker-compose-sbt.yml
    service: sbt
  volumes_from:
    - configs
    - data
