version: '2'
services:
  # Base container for sbt services.
  # In a separate file so that a container doesn't get created for it by default as this container would constantly restart.
  sbt:
    build:
      context: .
      dockerfile: Dockerfile-sbt
    expose:
      - "9000"
    entrypoint: /entrypoint.sh
    volumes:
      - ../:/code
      - ./entrypoints/sbt.sh:/entrypoint.sh
    restart: unless-stopped
