apiVersion: v1
kind: Service
metadata:
  name: collections
spec:
  type: NodePort
  selector:
    app: collections
  ports:
    - port: 9010
      name: collections
      nodePort: 32110
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: collections
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: collections
    spec:
      containers:
        - name: collections
          image: guardiangrid/collections:sihil_dockerise
          imagePullPolicy: Always
          args: 
            - -Dlogger.file=/opt/docker/conf/logback-docker.xml
            - -Dhttp.port=9010
          ports:
            - containerPort: 9010
          env:
            - name: AWS_CREDENTIAL_PROFILES_FILE
              value: /etc/aws/aws-credentials
          volumeMounts:
            - name: app-config-volume
              mountPath: /etc/grid
            - name: aws-credentials-config-volume
              mountPath: /etc/aws
          resources:
            limits:
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /management/healthcheck
              port: 9010
            initialDelaySeconds: 30
            periodSeconds: 3
      volumes:
        - name: app-config-volume
          configMap:
            name: collections
        - name: aws-credentials-config-volume
          configMap:
            name: aws-credentials