apiVersion: v1
kind: Service
metadata:
  name: cropper
spec:
  type: NodePort
  selector:
    app: cropper
  ports:
    - port: 9006
      name: cropper
      nodePort: 32106
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cropper
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cropper
    spec:
      containers:
        - name: cropper
          image: guardiangrid/cropper:sihil_dockerise
          imagePullPolicy: IfNotPresent
          args: 
            - -Dlogger.file=/opt/docker/conf/logback-docker.xml
            - -Dhttp.port=9006
          ports:
            - containerPort: 9006
          env:
            - name: AWS_CREDENTIAL_PROFILES_FILE
              value: /etc/aws/aws-credentials
          volumeMounts:
            - name: app-config-volume
              mountPath: /etc/grid
            - name: aws-credentials-config-volume
              mountPath: /etc/aws
          resources:
            limits:
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /management/healthcheck
              port: 9006
            initialDelaySeconds: 30
            periodSeconds: 3
      volumes:
        - name: app-config-volume
          configMap:
            name: cropper
        - name: aws-credentials-config-volume
          configMap:
            name: aws-credentials
