apiVersion: v1
kind: Service
metadata:
  name: thrall
spec:
  type: NodePort
  selector:
    app: thrall
  ports:
    - port: 9002
      name: thrall
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: thrall
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: thrall
    spec:
      containers:
        - name: thrall
          image: guardiangrid/thrall:sihil_dockerise
          imagePullPolicy: IfNotPresent
          args: 
            - -Dlogger.file=/opt/docker/conf/logback-docker.xml
            - -Dhttp.port=9002
          ports:
            - containerPort: 9002
          env:
            - name: AWS_CREDENTIAL_PROFILES_FILE
              value: /etc/aws/aws-credentials
          volumeMounts:
            - name: app-config-volume
              mountPath: /etc/grid
            - name: aws-credentials-config-volume
              mountPath: /etc/aws
          resources:
            limits:
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /management/healthcheck
              port: 9002
            initialDelaySeconds: 30
            periodSeconds: 3
      volumes:
        - name: app-config-volume
          configMap:
            name: thrall
        - name: aws-credentials-config-volume
          configMap:
            name: aws-credentials
