name: Grid CI
on: [pull_request]
jobs:
  JSBuild:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.16.1]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Kahuna
        working-directory: ./kahuna
        run: |
          npm install
          npm test
      - name: Image Counter Lambda
        working-directory: ./image-counter-lambda
        run: |
          npm install
          npm test
      - name: S3Watcher
        working-directory: ./s3watcher/lambda
        run: |
          npm install
          npm run build
      - name: Reaper
        working-directory: ./reaper
        run: |
          npm install
          npm run riffraff-artefact
  ScalaBuild:
    runs-on: ubuntu-18.04
    services:
      elasticsearch:
        image: elasticsearch:7.5.2
        # Wait for elasticsearch to report healthy before continuing.
        # see https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml#L28
        options: -e "discovery.type=single-node" --expose 9200 --health-cmd "curl localhost:9200/_cluster/health" --health-interval 10s --health-timeout 5s --health-retries 10
      localstack:
        image: localstack/localstack:0.10.8
        env:
          SERVICES: kinesis:4568,dynamodb:4569
          DEFAULT_REGION: eu-west-1
          KINESIS_ERROR_PROBABILITY: 0.0
          PORT_WEB_UI: 5050
        ports:
          - 5050:5050
          - 4568:4568
          - 4569:4569
        options: >-
          --health-cmd "curl localhost:5050/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
    - uses: actions/checkout@v1
    - name: SBT
      uses: ./.github/actions/sbt
      env:
        USE_DOCKER_FOR_TESTS: false
        ES6_TEST_URL: http://elasticsearch:9200
        AWS_CBOR_DISABLE: true
        KINESIS_ENDPOINT: http://localstack:4568
        DYNAMODB_ENDPOINT: http://localstack:4569
      with:
        args: clean compile test
