# This action runs every day at 6 AM and on every push
# If the branch it's running on is main then it will run snyk monitor (reports vulnerabilities to snyk.io)
# Otherwise it will run snyk test
name: Snyk

on:
  schedule:
    - cron: "0 6 * * *"
  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  snyk-monitor:
    runs-on: ubuntu-latest
    env:
      SNYK_COMMAND: monitor
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Get node version
        run: echo NODE_VERSION=$(cat .nvmrc) >> $GITHUB_ENV

      - uses: snyk/actions/setup@0.3.0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"

      - name: Snyk monitor scala
        run: snyk monitor --file=./build.sbt
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk monitor node
        run: snyk monitor --all-projects --exclude=build.sbt
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

