# This action runs every day at 6 AM and on every push
# If the branch it's running on is main then it will run snyk monitor (reports vulnerabilities to snyk.io)
# Otherwise it will run snyk test
name: Snyk

on:
  schedule:
    - cron: "0 6 * * *"
  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  snyk-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Run Snyk to monitor for Node vulnerabilities
        uses: snyk/actions/node@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --org=guardian
          command: monitor --all-projects --exclude=quarantine-status,./

      - name: Run Snyk to check for Python vulnerabilities in
        uses: snyk/actions/python@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --org=guardian --project-name=${{ github.repository }} --file=./quarantine-status/requirements.txt
          command: monitor

      - name: Run Snyk to monitor Scala vulnerabilities
        uses: snyk/actions/scala@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --org=guardian --project-name=${{ github.repository }} --file=./build.sbt
          command: monitor
